AWSTemplateFormatVersion: 2010-09-09
Description: rds-backup

Parameters:
  ProjectName:
    Type: String
    Default: rds-backup
  DeploymentPackageKey:
    Type: String
    Description: An S3 object key pointing of a ZIP file, an archive of everything that is needed to run the Lambda function. It is the output of the Build stage of the pipeline.

Resources:
  LambdaRunnerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - lambda.amazonaws.com
      Path: /
      Policies:
        - PolicyName: rds-backup
          PolicyDocument:
            Version: 2012-10-17
            Statement:
            - Effect: Allow
              Resource: "*"
              Action:
              - rds:CreateDBSnapshot
              - rds:CopyDBSnapshot
              - rds:DeleteDBSnapshot
              - rds:DescribeDBInstances
              - rds:DescribeDBSnapshots
              - rds:DescribeReservedDBInstances
              - rds:ListTagsForResource
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          'Fn::ImportValue': !Sub '${ProjectName}-pipeline-artifacts-bucket'
        S3Key: !Ref DeploymentPackageKey
      FunctionName: rds-backup
      Handler: app/index.handler
      Role: !GetAtt LambdaRunnerRole.Arn
      Runtime: nodejs6.10
      Timeout: 60 # can be 1 - 300 seconds

  PermissionForEventsToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LambdaFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt Trigger.Arn

  Trigger:
    Type: AWS::Events::Rule
    Properties:
      Description: Trigger snapshot backup on a schedule
      ScheduleExpression: rate(1 day)
      State: ENABLED
      Targets:
        - Arn: !GetAtt LambdaFunction.Arn
          Id: rds-backup

Outputs:
  LambdaFunction:
    Description: The ARN of the created Lambda function
    Value: !GetAtt LambdaFunction.Arn
